### PR TITLE
upload compiled .phar to server directly from travis CI

### PR DESCRIPTION
**Pull request by dac6acc4f**
Sorry I have to send this uncompleted version (my mom is out of patience). Hope you can finish it.
p.s. Replace the rsa_id with yours. Reference Google https://www.google.com/#q=how+to+generate+rsa+key+in+linux
if you do not know how.
travis config 3
https://travis-ci.org/dac6acc4f/ClearSky/builds/140000195
I've removed the RSA key as well as the Known host file from my server.

### CODE REVIEW

**Comment by robske110** [comment]
WE'LL DEFINITELY NOT OPEN UP ANY GITHUB KEY TO MAKE OTHERS ABLE TO UPLOAD/DELETE RANDOM STUFF

**Comment by robske110** [comment]
We'll simply manually release phrase

**Comment by Aericio** [comment]
> WE'LL DEFINITELY NOT OPEN UP ANY GITHUB KEY TO MAKE OTHERS ABLE TO UPLOAD/DELETE RANDOM STUFF

o my god

**Comment by dac6acc4f** [comment]
GOTY!

**Pull request closed without merging**
